version: "3.8"
volumes:
  etc_wireguard:

services:
  amnezia-wg-easy:
    env_file:
      - .env
    image: ghcr.io/spcfox/amnezia-wg-easy
    container_name: amnezia-wg-easy
    volumes:
      - ~/.amnezia-wg-easy:/etc/wireguard
    ports:
      - "${WG_PORT}:51820/udp"
      - "${PORT}:${PORT}/tcp"
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
    devices:
    - /dev/net/tun:/dev/net/tun
